# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

matrix:
  include:
    - env: DB=mysql; MW=REL1_27; DOCTRINE=1.4.0; ZENDCACHE=2.3.7; TYPE=coverage
      php: 5.6
    - env: ZENDCACHE=2.3.7; PHPUNIT=4.8.*
      php: 5.4
    - env: TYPE=UNIT;
      php: '7'
    - env: TYPE=UNIT; PHPUNIT=4.8.*
      php: hhvm
  allow_failures:
    - env: TYPE=UNIT; PHPUNIT=4.8.*

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-cache.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh
